# Site settings
title: Data Science Projects
email: jayhoc@middlebury.edu
description: > # this means to ignore newlines until "baseurl:"
baseurl: "" # the subpath of your site, e.g. /blog/
url: "jh-chung.github.io" # the base hostname & protocol for your site

twitter_username:
github_username: jh-chung

# Build settings
markdown: kramdown
